### ISSUE TITLE
pre-emphasis/de-emphasis

### ISSUE THREAD

**Issue by arijit17** [deepakbaby/isegan#1]
Hi @deepakbaby :

There is trainable pre-emphasis layer, but as far as I see, trainable de-emphasis is missing, isn't it?

**Comment by deepakbaby** [comment]
Hi @arijit17,
Yes that ist rue. The de-emphasis might be done the decoder automatically since our targets are de-emphasised signals.

It may be a good idea to add a de-emphasis layer at the output. If you try that, do let me know if it helped.

Deepak

**Comment by arijit17** [comment]
Hi @deepakbaby : thanks. But, ideally, de-emphasis should be an IIR-filter. How would you implement IIR-filter with (transposed) convolutional layers?

**Comment by deepakbaby** [comment]
Indeed. So I think it is better to leave the de-emphasis part to the decoder.
