### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by betegon** [deepakbaby/isegan#2]
Hi @deepakbaby 

I just reviewed your paper (congrats for that, so good!) and I will like to give it a try. 

Could you provide pre-trained weights of any configuration? This way people could check the functionality as the time consumed denoising files.

also, could you provide an example audio?
meaning a noisy audio and the cleaned audio, as a sanity check after installing all dependencies, so people can try the network and be sure everything work as expected.

Thank you for your time and effort,

regards!

**Comment by deepakbaby** [comment]
Hi @betegon,

I did this work when I was with my previous employer, and I dont have the weights anymore! May be I can train them again and provide the weights. But since the dataset is opensource and the whole code is available, it should be pretty straightforward to reproduce them.

Deepak

**Comment by betegon** [comment]
Thank you for your quick response @deepakbaby 

I am right now trying to train the network on my own, and I have several questions:

**1.)** Which configuration has the best overall score, which options?

**2.)** How many epochs were trained for obtaining paper results, and also, what hardware was used? I have GTX1080, and I am a little worried about not being able of keep the same batch size (_thus worsening the results_).

**3.)**  Which versions of Keras and Tensorflow are used?

**4.)** Could you add a LICENSE to the repository? So I could be able to contribute with some pull requests. (_I already found little bugs in some scripts_)

Thank you again!

**Comment by deepakbaby** [comment]
Hi,

Sorry for the late reply. The configurations can be found in the accompanying paper in arxiv. I used a Tesla Xp card for running the experiments. I think a GTX1080 should be fine.  The versions are added to the readme. I also have added a LICENSE. Please feel free to add pull requests.
Deepak

**Comment by betegon** [comment]
Hi @deepakbaby 

Thank you so much for your help!

**Comment by RitikaAg** [comment]
@betegon hi I am also on the lookout for pre trained weights, did you implement the model ? if so could you please upload the pretrained weights, I unfortunately don't have the necessary resources for training the model

**Comment by betegon** [comment]
Hi @RitikaAg I finally implemented the model, but I do know hold the weights neither the code, as I didn't use this model.
I suggest you to checkout [https://github.com/microsoft/DNS-Challenge]( https://github.com/microsoft/DNS-Challenge) . Easy to use, with pretrained model included.
