### ISSUE TITLE
KeyError: 'Gtanh'

### ISSUE THREAD

**Issue by betegon** [deepakbaby/isegan#3]
Hi @deepakbaby 

Running the following command I encountered an error:
```bash
python run_isegan.py 
```
The error is:

> Traceback (most recent call last):
  File "run_isegan.py", line 117, in <module>
    G = generator(opts)
  File "/home/betegon/isegan/models.py", line 120, in generator
    if opts['Gtanh']:
KeyError: 'Gtanh'

It comes from the following line of code in `models.py`:

```python
 # Add tanh of G uses tanh activation
if opts['Gtanh']:
    dec_out = Activation('tanh')(dec_out)   
```

The error is pretty easy to understand, there is  no key called `Gtanh` in the dictionary `opts`, passed as argument when calling `Generator(opts)` from `run_isegan.py`. So it will be as easy as adding it as a Boolean in `run_isegan.py`, i.e.,:

```python
opts['Gtanh'] = True # or false if better.
```

So my question is:

**Is it better to use `tanh` activation or not?**

Just let me know if you want me to make a pull request (but first you should add a LICENSE to the repository).

thanks a lot,

kind regards!

**Comment by deepakbaby** [comment]
Hi @betegon,

Sorry for the late reply. Indeed it was something I added during the development phase of the algorithm. And adding tanh did not help. I will remove it and commit a new version.

Thanks for pointing that out.
Deepak

**Comment by betegon** [comment]
Perfect, thank you!
