### ISSUE TITLE
real-time

### ISSUE THREAD

**Issue by msaad1311** [deepakbaby/isegan#8]
Hello. congrats on the awesome work. I was just wondering whether we can use the model to do real time noise cancellation?

**Comment by deepakbaby** [comment]
Hi @msaad1311,
Right now the model uses a very long window of ~1second, which would affect the real time application. An alternative might be to use shorter window lengths. Further optimizations are also possible like reducing the number of layers, filter length, number of filters per layer, etc.. Finally, it will also depend on your hardware and you might need further optimizations there, but I am not an expert on that.
